import gzip
import shutil
import urllib.request
import zipfile
import os
from PIL import Image

# NOTE: This script was written with AI assistance,
# so some parts may be less efficient or more verbose than necessary.

BASE_FOLDER = "textures"
ITEMS_FOLDER = "gui/items"
TERRAIN_FOLDER = "terrain"
GUI_FOLDER = "gui"
MOB_FOLDER = "mob"
FONT_FOLDER = "font"
TEMP_FOLDER = "temp"
CACHE_FOLDER = ".cache"  # downloads, kept out of temp so they stay out of the zip

ATLAS_SIZE = 256
TILE_SIZE = 16

# default.png is built from unscii, an 8x8 bitmap font.
UNSCII_VARIANT = "unscii-8-thin"
UNSCII_URL = "http://viznut.fi/unscii/{variant}.hex"

# GNU Unifont fills the few cells unscii has no glyph for. It is drawn 8x16, so
# those get squeezed down; It's also how the blocky block game fallback to.
UNIFONT_VERSION = "17.0.05"
UNIFONT_URL = ("https://ftp.gnu.org/gnu/unifont/unifont-{version}/"
               "unifont_all-{version}.hex.gz")

FONT_NOTICE = """\
font/default.png was generated by make_pack.py. It was not drawn by the LibreProg
artists.

Nearly all of it is unscii ({variant}) by Viznut, which is in the public domain:
http://viznut.fi/unscii/

{count} cell(s) that unscii has no glyph for were taken from GNU Unifont {version},
copyright Roman Czyborra, Paul Hardy and others, dual licensed under the SIL Open
Font License 1.1 and the GNU General Public License version 2 or later with the
GNU Font Embedding Exception. Those terms cover this one file; the rest of the
pack is BSD 3-Clause, as in the LibreProg repository.

https://unifoundry.com/unifont/
"""

FONT_CELL = 8
FONT_SIZE = FONT_CELL * 16

# Unifont's metrics, measured off its own .hex data.
UNIFONT_MAIN_TOP = 3
UNIFONT_BASELINE = 13
UNIFONT_DESCENDER = 15

# Box drawing has to keep meeting the cell edges and the shades have to keep their
# dither, so neither gets fitted to the text baseline.
BOX_DRAWING = range(0x2500, 0x2580)
BLOCK_ELEMENTS = range(0x2580, 0x25A0)
SHADES = range(0x2591, 0x2594)

# ./terrain.png
terrainMap = {
    "grass_top_base": [0,0],
    "stone": [1,0],
    "dirt": [2,0],
    "grass_side_base": [3,0],
    "planks": [4,0],
    "stone_slab_side": [5,0],
    "stone_slab_top": [6,0],
    "bricks": [7,0],
    "tnt_side": [8,0],
    "tnt_top": [9,0],
    "tnt_bottom": [10,0],
    "cobwebs": [11,0],
    "rose": [12,0],
    "dandelion": [13,0],
    "portal_placeholder": [14,0],
    "oak_sapling": [15,0],
    "cobblestone": [0,1],
    "bedrock": [1,1],
    "sand": [2,1],
    "gravel": [3,1],
    "oak_log_side": [4,1],
    "log_top": [5,1],
    "iron_block": [6,1],
    "gold_block": [7,1],
    "diamond_block": [8,1],
    "chest_top": [9,1],
    "chest_side": [10,1],
    "chest_front": [11,1],
    "red_mushroom": [12,1],
    "brown_mushroom": [13,1],
    "fire_placeholder_0": [15,1],
    "gold_ore": [0,2],
    "iron_ore": [1,2],  
    "coal_ore": [2,2],
    "bookshelf": [3,2],
    "mossy_cobblestone": [4,2],
    "obsidian": [5,2],
    "grass_side_overlay": [6,2],
    "tallgrass": [7,2],
    "grass_top_overlay": [8,2],
    "double_chest_front_left": [9,2],
    "double_chest_front_right": [10,2],
    "crafting_table_top": [11,2],
    "furnace_front": [12,2],
    "furnace_side": [13,2],
    "dispenser_front": [14,2],
    "fire_placeholder_1": [15,2],
    "sponge": [0,3],
    "glass": [1,3],
    "diamond_ore": [2,3],
    "redstone_ore": [3,3],
    "oak_leaves_transparent": [4,3],
    "oak_leaves_opaque": [5,3],
    "deadbush": [7,3],
    "fern": [8,3],
    "double_chest_back_left": [9,3],
    "double_chest_back_right": [10,3],
    "crafting_table_side": [11,3],
    "crafting_table_front": [12,3],
    "lit_furnace_front": [13,3],
    "furnace_top": [14,3],
    "spruce_sapling": [15,3],
    "white_wool": [0,4],
    "monster_spawner": [1,4],
    "snow": [2,4],
    "ice": [3,4],
    "grass_side_snow": [4,4],
    "cactus_top": [5,4],
    "cactus_side": [6,4],
    "cactus_bottom": [7,4],
    "clay": [8,4],
    "sugarcane": [9,4],
    "noteblock": [10,4],
    "jukebox_top": [11,4],
    "birch_sapling": [15,4],
    "torch": [0,5],
    "wooden_door_top": [1,5],
    "iron_door_top": [2,5],
    "ladder": [3,5],
    "trapdoor": [4,5],
    "farmland_wet": [6,5],
    "farmland_dry": [7,5],
    "wheat_stage_0": [8,5],
    "wheat_stage_1": [9,5],
    "wheat_stage_2": [10,5],
    "wheat_stage_3": [11,5],
    "wheat_stage_4": [12,5],
    "wheat_stage_5": [13,5],
    "wheat_stage_6": [14,5],
    "wheat_stage_7": [15,5],
    "lever": [0,6],
    "wooden_door_bottom": [1,6],
    "iron_door_bottom": [2,6],
    "redstone_torch_on": [3,6],
    "pumpkin_top": [6,6],
    "netherrack": [7,6],
    "soul_sand": [8,6],
    "glowstone": [9,6],
    "sticky_piston_front": [10,6],
    "piston_front": [11,6],
    "piston_side": [12,6],
    "piston_bottom": [13,6],
    "piston_front_inside": [14,6],
    "rail_turn": [0,7],
    "black_wool": [1,7],
    "gray_wool": [2,7],
    "redstone_torch_off": [3,7],
    "spruce_log_side": [4,7],
    "birch_log_side": [5,7],
    "pumpkin_side": [6,7],
    "pumpkin_front": [7,7],
    "jack_o_lantern_front": [8,7],
    "cake_top": [9,7],
    "cake_outside": [10,7],
    "cake_inside": [11,7],
    "cake_bottom": [12,7],
    "rail_straight": [0,8],
    "red_wool": [1,8],
    "pink_wool": [2,8],
    "redstone_repeated_off": [3,8],
    "spruce_leaves_transparent": [4,8],
    "spruce_leaves_opaque": [5,8],
    "bed_top_foot": [6,8],
    "bed_top_head": [7,8],
    "cake_item": [12,8],
    "lapis_lazuli_block": [0,9],
    "green_wool": [1,9],
    "lime_wool": [2,9],
    "redstone_repeater_on": [3,9],
    "bed_bottom_foot": [4,9],
    "bed_side_foot": [5,9],
    "bed_side_head": [6,9],
    "bed_bottom_head": [7,9],
    "lapis_lazuli_ore": [0,10],
    "brown_wool": [1,10],
    "yellow_wool": [2,10],
    "powered_rail_off": [3,10],
    "redstone_dust_cross": [4,10],
    "redstone_dust_line": [5,10],
    "sandstone_top": [0,11],
    "blue_wool": [1,11],
    "light_blue_wool": [2,11],
    "powered_rail_on": [3,11],
    "sandstone_side": [0,12],
    "purple_wool": [1,12],
    "magenta_wool": [2,12],
    "activator_rail": [3,12],
    "sandstone_bottom": [0,13],
    "cyan_wool": [1,13],
    "orange_wool": [2,13],
    "light_gray_wool": [1,14],
    "breaking_stage_0": [0,15],
    "breaking_stage_1": [1,15],
    "breaking_stage_2": [2,15],
    "breaking_stage_3": [3,15],
    "breaking_stage_4": [4,15],
    "breaking_stage_5": [5,15],
    "breaking_stage_6": [6,15],
    "breaking_stage_7": [7,15],
    "breaking_stage_8": [8,15],
    "breaking_stage_9": [9,15],
    "water": [[13,12],[14,12],[15,12],[14,13],[15,13]],
}

# ./gui/items.png
itemMap = {
    "leather_helmet": [0,0],
    "chainmail_helmet": [1,0],
    "iron_helmet": [2,0],
    "diamond_helmet": [3,0],
    "gold_helmet": [4,0],
    "flint_and_steel": [5,0],
    "flint": [6,0],
    "coal": [7,0],
    "string": [8,0],
    "seeds": [9,0],
    "apple": [10,0],
    "golden_apple": [11,0],
    "egg": [12,0],
    "sugar": [13,0],
    "snowball": [14,0],
    "leather_chestplate": [0,1],
    "chainmail_chestplate": [1,1],
    "iron_chestplate": [2,1],
    "diamond_chestplate": [3,1],
    "gold_chestplate": [4,1],
    "bow": [5,1],
    "brick": [6,1],
    "iron_ingot": [7,1],
    "feather": [8,1],
    "wheat": [9,1],
    "painting": [10,1],
    "sugar_cane": [11,1],
    "bone": [12,1],
    "cake": [13,1],
    "slimeball": [14,1],
    "leather_leggings": [0,2],
    "chainmail_leggings": [1,2],
    "iron_leggings": [2,2],
    "diamond_leggings": [3,2],
    "gold_leggings": [4,2],
    "arrow": [5,2],
    "quiver": [6,2],
    "gold_ingot": [7,2],
    "gunpowder": [8,2],
    "bread": [9,2],
    "sign": [10,2],
    "wooden_door": [11,2],
    "iron_door": [12,2],
    "bed": [13,2],
    "leather_boots": [0,3],
    "chainmail_boots": [1,3],
    "iron_boots": [2,3],
    "diamond_boots": [3,3],
    "gold_boots": [4,3],
    "stick": [5,3],
    "compass": [6,3],
    "diamond": [7,3],
    "redstone_dust": [8,3],
    "clay_ball": [9,3],
    "paper": [10,3],
    "book": [11,3],
    "map": [12,3],
    "wooden_sword": [0,4],
    "stone_sword": [1,4],
    "iron_sword": [2,4],
    "diamond_sword": [3,4],
    "gold_sword": [4,4],
    "fishing_rod": [5,4],
    "clock": [6,4],
    "bowl": [7,4],
    "mushroom_stew": [8,4],
    "glowstone_dust": [9,4],
    "bucket": [10,4],
    "water_bucket": [11,4],
    "lava_bucket": [12,4],
    "milk_bucket": [13,4],
    "black_dye": [14,4],
    "gray_dye": [15,4],
    "wooden_shovel": [0,5],
    "stone_shovel": [1,5],
    "iron_shovel": [2,5],
    "diamond_shovel": [3,5],
    "gold_shovel": [4,5],
    "fishing_rod_cast": [5,5],
    "redstone_repeater": [6,5],
    "raw_porkchop": [7,5],
    "cooked_porkchop": [8,5],
    "raw_fish": [9,5],
    "cooked_fish": [10,5],
    "cookie": [12,5],
    "shears": [13,5],
    "red_dye": [14,5],
    "pink_dye": [15,5],
    "wooden_pickaxe": [0,6],
    "stone_pickaxe": [1,6],
    "iron_pickaxe": [2,6],
    "diamond_pickaxe": [3,6],
    "gold_pickaxe": [4,6],
    "leather": [9,6],
    "saddle": [10,6],
    "green_dye": [14,6],
    "lime_dye": [15,6],
    "wooden_axe": [0,7],
    "stone_axe": [1,7],
    "iron_axe": [2,7],
    "diamond_axe": [3,7],
    "gold_axe": [4,7],
    "brown_dye": [14,7],
    "yellow_dye": [15,7],
    "wooden_hoe": [0,8],
    "stone_hoe": [1,8],
    "iron_hoe": [2,8],
    "diamond_hoe": [3,8],
    "gold_hoe": [4,8],
    "minecart": [9,8],
    "boat": [10,8],
    "blue_dye": [14,8],
    "light_blue_dye": [15,8],
    "minecart_with_chest": [9,9],
    "purple_dye": [14,9],
    "magenta_dye": [15,9],
    "minecart_with_furnace": [9,10],
    "cyan_dye": [14,10],
    "orange_dye": [15,10],
    "light_gray_dye": [14,11],
    "white_dye": [15,11],
    "record_13": [0,15],
    "record_cat": [1,15],
}

# ./
rootFiles = [
    "pack",
    "particles",
]

# ./
mobFiles = [
    "char",
    "chicken",
    "cow",
    "creeper",
    "ghast",
    "ghast_fire",
    "pig",
    "pigman",
    "pigzombie",
    "saddle",
    "sheep",
    "sheep_fur",
    "silverfish",
    "skeleton",
    "slime",
    "spider",
    "spider_eyes",
    "squid",
    "wolf",
    "wolf_angry",
    "wolf_tame",
    "zombie",
]

# ./gui/
guiFiles = [
    "background",
    "container",
    "crafting",
    "furnace",
    "gui",
    "icons",
    "inventory",
    "logo",
    "particles",
    "slot",
    "trap",
    "unknown_pack",
]

# ./font/
fontFiles = [
    "default",
]

# default.png is laid out as code page 437, which is where the box drawing and the
# Greek in its upper half come from. Hacky hacky to make it work for non "compliant"
# glyphs.
fontOverrides = {
    # The symbols code page 437 draws at 0x01-0x1F, where Python's codec hands
    # back control codes instead. Unifont has all of them at 8 pixels wide.
    0x01: 0x263A,  # white smiling face      0x02: black smiling face
    0x02: 0x263B,
    0x03: 0x2665,  # heart                   0x04: diamond
    0x04: 0x2666,
    0x05: 0x2663,  # club                    0x06: spade
    0x06: 0x2660,
    0x07: 0x2022,  # bullet                  0x08: inverse bullet
    0x08: 0x25D8,
    0x09: 0x25CB,  # circle                  0x0A: inverse circle
    0x0A: 0x25D9,
    0x0B: 0x2642,  # mars                    0x0C: venus
    0x0C: 0x2640,
    0x0D: 0x266A,  # eighth note             0x0E: beamed eighth notes
    0x0E: 0x266B,
    0x0F: 0x263C,  # sun
    0x10: 0x25BA,  # right pointer           0x11: left pointer
    0x11: 0x25C4,
    0x12: 0x2195,  # up down arrow           0x13: double exclamation
    0x13: 0x203C,
    0x14: 0x00B6,  # pilcrow                 0x15: section sign
    0x15: 0x00A7,
    0x16: 0x25AC,  # black rectangle         0x17: up down arrow with base
    0x17: 0x21A8,
    0x18: 0x2191,  # up arrow                0x19: down arrow
    0x19: 0x2193,
    0x1A: 0x2192,  # right arrow             0x1B: left arrow
    0x1B: 0x2190,
    0x1C: 0x221F,  # right angle             0x1D: left right arrow
    0x1D: 0x2194,
    0x1E: 0x25B2,  # up triangle             0x1F: down triangle
    0x1F: 0x25BC,

    # And the cells where the sheet parts ways with the codepage. Blocky game trades
    # away four of cp437's currency and maths signs for letters European languages
    # actually need, which is worth keeping if the pack is to be a drop-in.
    0x7F: 0x2302,  # house, which cp437 has but Python's codec reads as DEL
    0x9B: 0x00F8,  # o slash, where cp437 has a cent sign
    0x9D: 0x00D8,  # O slash, where cp437 has a yen sign
    0x9E: 0x00D7,  # multiplication, where cp437 has a peseta sign
    0xA9: 0x00AE,  # registered, where cp437 has a reversed not sign
    0xE1: 0x03B2,  # beta, where cp437 has a sharp s
    0xE6: 0x03BC,  # greek mu, where cp437 has the micro sign
    0xED: 0x2205,  # empty set, where cp437 has phi
    0xEE: 0x2208,  # element of, where cp437 has epsilon
}

# The 0x01-0x1F symbols sit centred in their cell like the line art does, rather
# than being shoved left the way a letter is.
fontSymbols = frozenset(range(0x01, 0x20))

def get_texture_path(texture_name, folder):
    return os.path.join(BASE_FOLDER, folder, f"{texture_name}.png")

# Create empty atlas
def generate_atlas(mapping, atlas_name):
    missing = 0
    atlas = Image.new("RGBA", (ATLAS_SIZE, ATLAS_SIZE))

    for name, coords in mapping.items():
        positions = coords if isinstance(coords[0], list) else [coords]
        path = get_texture_path(name, atlas_name)

        if not os.path.exists(path):
            #print(f"Missing: {path}")
            missing += 1
            continue

        tile = Image.open(path).convert("RGBA")

        if tile.size != (TILE_SIZE, TILE_SIZE):
            print(f"Wrong size: {path} -> {tile.size}")
            continue

        for (x, y) in positions:
            atlas.paste(tile, (x * TILE_SIZE, y * TILE_SIZE))

    print(f"{atlas_name}.png progress: {len(mapping) - missing}/{len(mapping)}")

    # Save atlas
    atlas.save(os.path.join(TEMP_FOLDER, f"{atlas_name}.png"))

def copy_files(file_list, base_folder, ext="png"):
    os.makedirs(os.path.join(TEMP_FOLDER, base_folder), exist_ok=True)
    missing = 0
    for file in file_list:
        src_path = os.path.join(BASE_FOLDER, base_folder, f"{file}.{ext}")
        dst_path = os.path.join(TEMP_FOLDER, base_folder, f"{file}.{ext}")

        if not os.path.exists(src_path):
            missing += 1
            continue

        shutil.copy(src_path, dst_path)

    print(f"{base_folder} ({ext}) progress: {len(file_list) - missing}/{len(file_list)}")

# Fetches a url once, keeping the result in the cache folder
def download(url, cache):
    if not os.path.exists(cache):
        os.makedirs(CACHE_FOLDER, exist_ok=True)
        print(f"Downloading {os.path.basename(cache)}...")
        with urllib.request.urlopen(url) as response, open(cache, "wb") as archive:
            shutil.copyfileobj(response, archive)
    return cache

# Reads a .hex font: one "codepoint:bitmap" pair per line, which is the format
# both unscii and Unifont ship in
def load_hex(path):
    opener = gzip.open if path.endswith(".gz") else open
    glyphs = {}
    with opener(path, "rt") as handle:
        for line in handle:
            codepoint, _, bitmap = line.strip().partition(":")
            if bitmap:
                glyphs[int(codepoint, 16)] = bitmap
    return glyphs

def fetch_unscii():
    cache = os.path.join(CACHE_FOLDER, f"{UNSCII_VARIANT}.hex")
    return load_hex(download(UNSCII_URL.format(variant=UNSCII_VARIANT), cache))

def fetch_unifont():
    cache = os.path.join(CACHE_FOLDER, f"unifont-{UNIFONT_VERSION}.hex.gz")
    return load_hex(download(UNIFONT_URL.format(version=UNIFONT_VERSION), cache))

# Splits a .hex bitmap into its rows, returning them and the glyph's width
def unpack_glyph(bitmap, height):
    digits = len(bitmap) // height
    rows = [int(bitmap[i * digits:(i + 1) * digits], 16) for i in range(height)]
    return rows, digits * 4

# Halves a row of pixels, for the occasional glyph drawn two cells wide
def squash_row(row, width):
    squashed = 0
    for column in range(width):
        if row >> (width - 1 - column) & 1:
            squashed |= 1 << (FONT_CELL - 1 - column * FONT_CELL // width)
    return squashed

# unscii is already drawn at 8x8, so its glyphs need nothing doing to them
def unscii_glyph(bitmap):
    rows, width = unpack_glyph(bitmap, FONT_CELL)
    return [squash_row(row, width) for row in rows] if width > FONT_CELL else rows

# How many enclosed gaps a row of pixels has, which at this size is most of what
# tells an 'a' apart from a blob
def count_holes(row):
    if not row:
        return 0
    span = bin(row)[2:].rstrip("0")
    return len([gap for gap in span.split("1") if gap])

# Which of Unifont's 16 rows each of the cell's 8 rows is built from
def row_plan(codepoint):
    if codepoint in SHADES:
        # These repeat every two rows, so the top half already is the pattern.
        # Merging pairs, the way the line art below needs, would fill them solid.
        return [[row] for row in range(FONT_CELL)]

    if codepoint in BOX_DRAWING or codepoint in BLOCK_ELEMENTS:
        return [[2 * row, 2 * row + 1] for row in range(FONT_CELL)]

    plan = [[] for _ in range(FONT_CELL)]
    for row in range(UNIFONT_MAIN_TOP):
        plan[0].append(row)
    span = UNIFONT_BASELINE - UNIFONT_MAIN_TOP + 1
    for row in range(UNIFONT_MAIN_TOP, UNIFONT_BASELINE + 1):
        plan[1 + (row - UNIFONT_MAIN_TOP) * (FONT_CELL - 2) // span].append(row)
    for row in range(UNIFONT_BASELINE + 1, UNIFONT_DESCENDER + 1):
        plan[FONT_CELL - 1].append(row)
    return plan

# Squeezes one 8x16 Unifont glyph into the 8x8 cell. Only the handful of cells
# unscii is missing come through here.
def unifont_glyph(bitmap, codepoint):
    rows, width = unpack_glyph(bitmap, 16)
    linework = codepoint in BOX_DRAWING or codepoint in BLOCK_ELEMENTS

    fitted = []
    for sources in row_plan(codepoint):
        merged = 0
        for source in sources:
            merged |= rows[source]

        # Merging the row that closes a bowl with the stem row beside it seals the
        # counter shut and the letter reads as a smudge. Where that would happen,
        # keep whichever row carries the most ink and drop the other: the stem it
        # belonged to is still drawn by the rows above and below it.
        if not linework and len(sources) == 2:
            above, below = rows[sources[0]], rows[sources[1]]
            if count_holes(merged) < max(count_holes(above), count_holes(below)):
                merged = max(above, below, key=lambda row: bin(row).count("1"))

        fitted.append(squash_row(merged, width) if width > FONT_CELL else merged)
    return fitted

# Letters sit against the left edge of their cell, because the game measures a
# glyph's advance from its rightmost opaque column and that is what makes text
# space proportionally. Line art and the symbols stay put, or they would stop
# lining up from one cell to the next.
def place(rows, centred):
    if centred or not any(rows):
        return rows
    shift = min(FONT_CELL - row.bit_length() for row in rows if row)
    return [row << shift for row in rows]

# Build font/default.png, unless the artists have drawn one
def generate_font():
    if os.path.exists(os.path.join(BASE_FOLDER, FONT_FOLDER, "default.png")):
        print(f"{FONT_FOLDER}/default.png: drawn by hand, left alone")
        return

    try:
        unscii = fetch_unscii()
    except Exception as error:
        print(f"{FONT_FOLDER}/default.png: skipped, no unscii ({error})")
        return

    # Cell 0x00 stays blank, as the codepage has nothing there either.
    layout = dict(fontOverrides)
    for cell in range(0x20, 0x100):
        layout.setdefault(cell, ord(bytes([cell]).decode("cp437")))

    unifont = {}
    if any(codepoint not in unscii for codepoint in layout.values()):
        try:
            unifont = fetch_unifont()
        except Exception as error:
            print(f"{FONT_FOLDER}/default.png: no Unifont to fill unscii's gaps ({error})")

    sheet = Image.new("RGBA", (FONT_SIZE, FONT_SIZE))
    pixels = sheet.load()
    drawn = borrowed = 0
    for cell, codepoint in sorted(layout.items()):
        if codepoint in unscii:
            rows = unscii_glyph(unscii[codepoint])
        elif codepoint in unifont:
            rows = unifont_glyph(unifont[codepoint], codepoint)
            borrowed += 1
        else:
            continue

        centred = (cell in fontSymbols or codepoint in BOX_DRAWING
                   or codepoint in BLOCK_ELEMENTS)
        left = (cell % 16) * FONT_CELL
        top = (cell // 16) * FONT_CELL
        for y, row in enumerate(place(rows, centred)):
            for x in range(FONT_CELL):
                if row >> (FONT_CELL - 1 - x) & 1:
                    pixels[left + x, top + y] = (255, 255, 255, 255)
        drawn += 1

    os.makedirs(os.path.join(TEMP_FOLDER, FONT_FOLDER), exist_ok=True)
    sheet.save(os.path.join(TEMP_FOLDER, FONT_FOLDER, "default.png"))
    with open(os.path.join(TEMP_FOLDER, FONT_FOLDER, "README.txt"), "w") as notice:
        notice.write(FONT_NOTICE.format(variant=UNSCII_VARIANT, count=borrowed,
                                        version=UNIFONT_VERSION))

    print(f"{FONT_FOLDER}/default.png progress: {drawn}/{len(layout)} "
          f"({UNSCII_VARIANT}, {borrowed} borrowed from GNU Unifont {UNIFONT_VERSION})")

# Create temp folder
if not os.path.exists(TEMP_FOLDER):
    os.mkdir(TEMP_FOLDER)
if not os.path.exists(os.path.join(TEMP_FOLDER, "gui")):
    os.mkdir(os.path.join(TEMP_FOLDER, "gui"))

# Generate atlases
generate_atlas(terrainMap, TERRAIN_FOLDER)
generate_atlas(itemMap, ITEMS_FOLDER)

# Copy raw files
copy_files(guiFiles, GUI_FOLDER)
copy_files(mobFiles, MOB_FOLDER)
copy_files(fontFiles, FONT_FOLDER)
copy_files(rootFiles, ".")

# Fall back to Unifont for the font sheet while nobody has drawn one
generate_font()

# Copy .txt files from all subdirectories
import glob
for src_path in glob.glob(os.path.join(BASE_FOLDER, "**", "*.txt"), recursive=True):
    rel_path = os.path.relpath(src_path, BASE_FOLDER)
    dst_path = os.path.join(TEMP_FOLDER, rel_path)
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    shutil.copy(src_path, dst_path)

# Create texture pack zip
with zipfile.ZipFile("LibreProg.zip", "w") as zipf:
    for root, dirs, files in os.walk(TEMP_FOLDER):
        for file in files:
            full_path = os.path.join(root, file)
            rel_path = os.path.relpath(full_path, TEMP_FOLDER)
            zipf.write(full_path, rel_path)

# Cleanup temp folder
#shutil.rmtree(TEMP_FOLDER)
